site_name: 謹賀新年2017
description: 謹んで新年のお慶びを申し上げます

keywords:
  - 岩淵勇樹
  - butchi
  - butchi_y
  - 年賀状

url: https://butchi.github.io/nenga/2017/
facebook_app_id": 196651660681019
twitter_card_owner: "@butchi_y"
ogp_image_url: https://butchi.github.io/nenga/2017/ogp.jpg?v2017-01-01--1
favicon_url: favicon.ico